config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :my_portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'portfolio/:id', to:'my_portfolios#show', as: 'my_portfolio_show'

  get 'about-me', to:'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home' #setting root to pages/home url (i.e. localhost:3000)
end

app/models/my_portfolio.rb
class MyPortfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                reject_if: lambda { |attrs| attrs['name'].blank? }

  include Placeholder
  validates_presence_of :title, :body, :main_mage, :thumb_image

  def self.by_position
    order("position ASC ")
  end

  after_initialize :set_defaults

  def set_defaults
    self.main_mage ||= Placeholder.image_generator(height: '600', width: '400')
    self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
  end
end

app/controllers/my_portfolios_controller.rb
class MyPortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [:edit, :update, :show, :destroy]
  layout "my_portfolio"
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :edit, :sort]}, site_admin: :all

  def index
    @my_portfolio = MyPortfolio.by_position
  end

  def sort
      params[:order].each do |key, value|
        MyPortfolio.find(value[:id]).update(position: value[:position])
      end

       render body: nil
    end

  def new
    @my_portfolio = MyPortfolio.new
    3.times {@my_portfolio.technologies.build}
  end

  def create
    @my_portfolio = MyPortfolio.new(portfolio_params)

    respond_to do |format|
      if @my_portfolio.save
        format.html { redirect_to (my_portfolios_path), notice: 'Your portfolio was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @my_portfolio.update(portfolio_params)
        format.html { redirect_to (my_portfolios_path), notice: 'The record was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
  end

  def destroy
    @my_portfolio.destroy

    respond_to do |format|
      format.html { redirect_to my_portfolios_url, notice: 'Portfolio was successfully destroyed.' }
    end
  end

  private

  def portfolio_params
    params.require(:my_portfolio).permit(:title,
                                         :subtitle,
                                         :body,
                                         technologies_attributes: [:name]
                                        )
  end

  def set_portfolio_item
    @my_portfolio = MyPortfolio.find(params[:id])
  end
end

app/helpers/my_portfolios_helper.rb
module MyPortfoliosHelper
end

app/views/my_portfolios/_form.html.erb
<%= form_with(model: @my_portfolio, local: true) do |form| %>
<div class="row">
  <div class='col-md-6'>
    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :subtitle %>
      <%= form.text_field :subtitle, class: 'form-control' %>
    </div>
  </div>
  <div class="col-md-6">
    <div class="form-group">
      <%= form.label :body %>
      <%= form.text_area :body, class: 'form-control', rows: 13 %>
    </div>
  </div>
</div>

<hr>

<div class="col-md-12">
  <h2>Technologies Used:</h2>
  <div>
    <%= form.fields_for :technologies do |technolgy_form | %>
      <div class='form-group'>
        <%= technolgy_form.label :name %>
        <%= technolgy_form.text_field :name, class: 'form-control' %>
      </div>
    <% end %>
  </div>
  <div class="form-group">
    <%= form.submit 'Save Portfolio Item', class: 'btn btn-primary btn-block' %>
  </div>
</div>
<% end %>

app/views/my_portfolios/_my_portfolio.html.erb
<div class="card" data-id="<%= my_portfolio.id %>">
  <%= image_tag (my_portfolio.thumb_image) unless my_portfolio.thumb_image.nil? %>
  <p class="card-text">
    <span><%= link_to my_portfolio.title, my_portfolio_show_path(my_portfolio.id) %></span> <%= my_portfolio.subtitle %>
  </p>
</div>

app/views/my_portfolios/edit.html.erb
<div class="container portfolio-form">
  <h1>Edit this Portfolio Items</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/my_portfolios/index.html.erb
<div class="album text-muted">
<div class="container">
  <div class="row <%= "sortable" if logged_in?(:site_admin) %>">
    <%= render @my_portfolio %>
    </div>
  </div>
</div>

app/views/my_portfolios/new.html.erb
<div class="container portfolio-form">
  <h1>Create a Portfolio Item</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/my_portfolios/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7">
      <%= image_tag @my_portfolio.main_mage %>
    </div>

    <div class="col-md-5">
      <h1><%= @my_portfolio.title %></h1>

      <hr>

      <em><%= @my_portfolio.subtitle %></em>

      <p><%= @my_portfolio.body %></p>

      <hr>

      <h3>Technologies Used:</h3>

      <% @my_portfolio.technologies.each do | t | %>
      <p><%= t.name %></p>
      <% end %>
    </div>
  </div>
</div>